language: python
python:
    - 3.7
install:
    - pip install -U tox-travis
script: tox
deploy:
    provider: pypi
    distributions: sdist bdist_wheel
    user: goodchinas
    password:
        secure: Qw5XH0KeoKLXEdHDnbP3ZQa2+9NjtFLH9jxq2fkcc4XV/dwIaBQY1TWpy5SEMY3bz/V1BjaOe7toW5pheazpO/0Hn/6Aar2c4gAzhom7gbjNDr50EFPOWUam3vKfqDQaLWwEAY6zcZIFb1BaVApAYpIIyN+IxS8HHDxIbpKMg0rgCD0h2yhV46MOoTrdbSeaHPEwvWMzxRPA/eC+X1onUQrLjoq/JdAqc4udOKc3MFOtG7DkAP0eLjuSgM00P37nnANasYnzPJtAoj4ImiQ5v8fIRht9eKYpFIyaP12S/9Cy3zdNwDRyRhQubEmgPSuTlhtu4Q68gImFDCYnKkkcPsB6urs7hUZAnpiMu3beFeGi7UprUETppJHs0IQ4bZoHQeJA2nWvfyiAi9xoyuvPyjrVkkphYMXeAEeOjBo/6z2I+ydOrbgBheywIdgwrBToidmdbPePQxVRmNmIyZrDkqB1bXE7s0AtGQTTOj8ZjuwUGjdBHH6jI/arPZ+ytPf3EuWHhY2U+lN9d5LrjVHZ6x4l79bkyH+pHHUNN9PhqWQWBtcY08rVLug3NuIe9dXBtzG5CChnSmMy7UqPthLyuH9T5rWspJQlQalGdqdfSHp7jHlit4mGC2Nnep8hyI0iROqts7vGV47HKdmljd+J6LbmM1Adr/dPDug44pcEpek=
    true:
        tags: false
        #    branch: master
        repo: goodchinas/pyxq
        python: 3.7
