language: python
python:
    - 3.7
install:
    - pip install -U tox-travis
script: tox
deploy:
    provider: pypi
    distributions: "sdist bdist_wheel"
    skip_existing: true
    user: $PYPI_USER
    password: $PYPI_PASSWORD
    true:
        tags: false
        branch: master
        python: 3.7
