language: python
python:
- 3.7
install:
- pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: goodchinas
  password:
    secure: soolKNL/VMNdOWIrflg8MvWNHZRu6QEiOq8ifji63Ssh01Rm5XNOIe9nl90TSboar91BEFo26Ah2mkzY6qvA6jLE8kTGw+J3DjzKIl/MZ4iumEJoswMi8bRQJhPhlyawoYPARsqdc8iqBAuFMxd/d5OfpbzqGXBLua2U/7rNLfYfQVYSUH7BuJoRTIHGbn5ct833U099PZVr/oKKt+y/DR1pRhBAUwiSjl8J+qG58SCwKObOumlBP0a4HIrOoj95ICLc/FJwuYeYurLe9GH84S9tuLdTzlcypiivOkPPeGMZrkydXF/26HutTsK0vNEN8rxdjTprnonU0x2gAub2eBgk/zhEnpQJf9Tb+nZyQuCw4K0+iz2Tdr+pWkRAWp3DiV3Q7Lu/7ZHvbhcZ43EAbFG+7opTMEIaSgV5lw450Ie/6O2bm2YvcZut1tyfhxxdp3BbjVOJaAnsVnbFI+oT6JoFJ5yhspfjOc3jz+IkKnp4KpHxq93B3D+w06AkKi4jVix5Dp0tqThkbVCnJWFPQJ19UAZkj4piWSp9YuhrgouuhAfMR9uipCYj55Aj16D2AbpCm0Rd7rZ8cYOcwsjsIg6dkWvNIxKGaC4Xa0YFHiqptxj/bHR284kbuUoSOXCO2nKnl3DQMnXJbA3WQS8/Dd1fQnZN3TjXdo5Cz1tGFTs=
  true:
    tags: false
    branch: master
    python: 3.7
