language: python
python:
- 3.7
install:
- pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: goodchinas
  password:
    secure: ABdf1w0gTBrQk1C/VX4/HNUpmkRni2nzT4Tnv82FiuBB450V8NDr5aTNKQNkhI7KTxbEVrTnZ173DX5p0WC4NhEK1OsJaYEM222lqQX1z/v379Qemw7Gqdejr3QdRBVWS0/e+qNot+9e0sZKyoY0oLWH2vGCbl0sVTqoWtXNCCBcol7bZ9GdUlzxnB/178wzZZFI7JmD8uhN/YE8szeL2h7ZHnRwADcZmYXPStchT2bzDc6G3ksyTQ9UBzazWy5nSlxtm/A+QFrSO0gQSEWzHqA5I6PAjdJwx/WOVe3nqRHa1n7cA1IJNQLI/BRC50VIokunreAQRPfC+S38AKjtsPa+Tz3SWgwbi2+LrsBFHcUm+ydAG0U65rph4Zh97NCJ2UT1SYu8tvlhcOf2ZSyXbcBJW1yk5qSS5Ruqv6Bhm4YCxTVXNYVLxfy6A7FBgpWd7mt0eS3AFDT5hEh8JC+igd0UuK/cePBgrmLHg3Kk1vYSsXZvfYDzC82+BB2C/IJWwc4wvivtdN/kQYLaYW50fl7eA3gByK4QVoUFIwRHVfe3B7z1zsUkAk5s3KGIR8xPQcWVVKTrsRbzMD+PTw3hWCgtn2d14z+zRhGPlpCFef6CktGEayvXknNSu96DiCImvyUqPRzpcjwuAGtnTBUM7SO4cY4hvClNe8kDrqCB4IM=
  true:
    tags: false
    branch: master
    python: 3.7
