language: python
python:
- 3.7
install:
- pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: goodchinas
  password:
    secure: NuqUEgbdeKbBQFgCF2a6BA4izts7AzuhhVYW43d+cvty77wSEJrHgYBQNxg5XQon7S/egQX/vcDOggEyb+5R2HmXF0pNHtF3a8iYHqSMbhfabOvrm5M0qtPt4vuXwINqm01QWcqHnb/IzjvDWSjlTNNSNRulhPUucCAJO9oSn0hXppEJ0Qbb6mMvyjpLiX7X3ko8bQfbVtFHMWKwsC8OBCl47MSL6zw4IAzSjZaI8ihpCTGbgJZ7pv81/wU+Ye5NUD0ELVRUf77vWJE8Crd7nTokVJChxhKyBA7i7NbxO7BX1FWqO3xtzYEU0GCa4HTwenjv9pWWXISM8KlVOZssRX3RT6wB4WAvDFTg5DMIz1V9OKPreMtsfinGib8eOOrMT97OJzugsJqXsabzJA9+G84CnkBQlC+6+JPzK9o677S7tT5nKwsxXa+zWag1kw2cgTPALk/0TK30PUdLIrghlmWYP3v74n32YJYvOMWnjkYb2T9pRjgtu+rRx6XbSidIUoQNboYTwujUx/UYCLDbVOXMR/8D3TuwT0a1v/Ufd9G7K601Bl8zftJIZqyMTFEmpce1I2YXB91Ch1vQ/v3BMed6GuqtmTC0FpooJPjWimOLQ9n2J0hLUQjJi9+IWhPiAtgl5dYHZol/jzQUNP2MpSjPLykiX2NaHfniw+i1tn4=
  true:
    tags: false
    branch: master
    python: 3.7
