language: python
python:
- 3.7
install:
- pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: goodchinas
  password:
    secure: GC2mZ82FlZaEks9dpYJOEuC639MSp5jOvvQjspUcyXtBKYckrA1abTdZQJ1O5cWvyYJdlITTSqXBkqXWx8laI+nXiDmwez34QAG78sqQo05gC6irJAsH0GUlUmajSEM30sMpxjlW5+C8qWrIH/qJ+CQrgDTKMwBFF9zvwRwRmbPIuBfJPy14jDNLh8BfaWCer68SXWHn2Y+Qfs8Bbnk9FY33DC4LThzPPfzxS3wOzDcUb6uyXWbe/ubWYA/pHnFg8IDosLilQvWtasFRqHATTb+bazO0aUFlHpaLkvZ2fcUKCdd1DbFPJ7gFO1nsj2kSYiy3ldeb67cF6LchOGs8AJbwhYJRsAUe/pEWkUEnln1pSrrSbjWGZ35wf54A2CSSCUWfwZzLEMqJiRoUWRxsvVDLvHnNeTNErRTjropl6WeZz78XI9v4FX4IIqV4CBMNWDZ7zVttBVjdXIpsnfABHZE07fY+COliiHOHuZ0FPO0qozVvU2dJIGPa3q9d6iIQ3mwlvfnVKzLHPzYGhUxLgliAMAZyaZV0/YCshubxy4Q9qCBsUhFQR19BRWrpdizWVABQ+oD0/Pd9JtLhRmMRzw13GixO4r7WwkfFQVbnXgZqPqUe8Ab+WrCN3v32X8NHmHK07sI/W29eysNApr0x3CP1FcCaCg+cZAQ9HmFCe0k=
  true:
    tags: false
    repo: goodchinas/pyxq
    python: 3.7
