language: python
python:
- 3.7
install:
- pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: goodchinas
  password:
    secure: CbigRIXkudGCAtCQr2t2MTSY6PQScXvIaPMZa7oyVBK6iai1v47ZBby4/Vn3du9rXKCS1RS3i6Bcb89vJqUjNpcK+MQrMCMS68005Xg67NdNkshj/l+DmouaZm6Y+BRhZwVNLpcgMEu7F/pr88EJQX4B8+qz6ElPoFadia50t/Q6l0v97qBJN2ak5EkxcB0/Zgg3y+uNRoV4eLXDzPiUMQ7rX9+Ih7esAhFXkr+F3DRcw/ZvY4QKomFdzebhUIbIfai2wvlepVplRd6HoewGnwMtI/AmZj2P0OX/qsMCkIUosBnJFyedWhJYENtqDeDkVnwUMLAo9Av8pdq/7HZlt7ms25X21muIRl2J2DrdHgEX0tgJ/fvdAxiqMGerFDGQTjUzXh1SJT2/76+gklRBpag4b1x2yTk6upDfD5WK5sYQSPlKKgDgNZBg2utXXPhfx/hxxz8UcJlpqElZfIqNgduOOsQly7MuNHSQO9XtmB8MaeYbMxid2Gp6X02uCXn6431j4cGT0PLSs5jGnMWJ6Lv+RWOKjXGb91YACqOWWuUt+DjIOAw3p7z31aTSRLDvg5y9kycowEO8fwX1mwTqmyvJGLTpKb481F7kATAi9+SupTH46r7tlMq9L6svxbE2cSXnrjWiNycFB08BwE+ItdWs/vnpD9us61gt9Uw/0tw=
  true:
    tags: false
    branch: master
    python: 3.7
