language: python
python:
- 3.7
install:
- pip install -U tox-travis
- pip install pytest
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: goodchinas
  password:
    secure: kXWW3knXAYiLwGQtCZw1nFoa7Uo8VlybiV4IoP0MJlx25ea2Zz4m3Bwbv5M4yC18RrNUeQrpSKlwDCqk/VhNAbraWT6rOyPLY28+ALEEU5fKUicdnEFWjfgUbcObMKng7Mp6aBWDi6QohDOg7ypF949sStJvBkWUplyD5qqXYvgivHLvuYUAjiJsNRvEaCL4WWZJpey/v7wAePZSoozJjCrhx+nfCfS0xuvjgI0uLhq4QyUNwqIovGziwq5+TYO9L8/rgoxz0O/duizs6gbRfMxqxpht72ebBTsVwxiRVL9zd2c3wky3NcTpPOkrHHU89oKfw1YMHcdFho6GZDYvGexDrLDw9OXzwMlXZqptbXtf56SErqgUxjOqhfoHo1ulOxe00rEky0LIwxHXPnKgOeP5CACzoM3Sq0U+BAMi11dbSSjpq3tYOleNq4XoWSqBzOHAt2AKy8fDcoe/9StpWa2Nvs2yQ+PvV1x7Q7pkxjiNe1EAxvbn+cCLFc0DNYiNyhKpv4ACg0NgTVc3+epj72mQcjFJLwp6Ok8vgQJ+ldDcZeefwNhvixKf4Dl/VaF1bvaN4kBGbrxIe5NnbTBDcdA68mwZZm7/dgJ1TGSDZlaKuBDizRiXvZG8hd/85THVjJ5F/rHYhHtL08Wp7egvJHBJ5fZeiVJbfyucDY2EOs8=
  true:
    tags: false
    branch: master
    python: 3.7
